package ar.edu.ort.trabajopractico.navigation

sealed class RootScreen(val route: String) {
    object Onboarding : RootScreen("onboarding_root")
    object Login : RootScreen("login_root")
    object Home : RootScreen("home_root")
    object Profile : RootScreen("profile_root")
    object Setting : RootScreen("setting_root")
    object Account : RootScreen("account_root")
    object Address : RootScreen("address_root")
    object NotificationAccount : RootScreen("notification_account_root")
    object Notification : RootScreen("notification_root")
    object Search : RootScreen("search_root")
    object BestSeller : RootScreen("best_seller_root")
    object PaymentMethod : RootScreen("payment_method_root")
    object Privacy : RootScreen("privacy_root")
    object Security : RootScreen("security_root")
    object FAQ : RootScreen("faq_root")
    object ChangeEmail : RootScreen("change_email_root")
    object ChangePassword : RootScreen("change_password_root")
    object ProductDetail : RootScreen("product_detail_root")
    object Cart : RootScreen("cart_root")
    object CreateAccount: RootScreen ("create_account_root")
    object Favourites: RootScreen ("favourites_root")

}

sealed class LeafScreen(val route: String) {
    object OnBoarding : LeafScreen("onboarding")
    object Login : LeafScreen("login")
    object Home : LeafScreen("home")
    object Profile : LeafScreen("profile")
    object Setting : LeafScreen("setting")
    object ForgotPasswordEmail : LeafScreen("forgot_password_email")
    object ResetPassword : LeafScreen("reset_password")
    object Account : LeafScreen("account")
    object Address : LeafScreen("address")
    object NotificationAccount : LeafScreen("notification_account")
    object Notification: LeafScreen("notification")
    object Search : LeafScreen("search")
    object PaymentMethod : LeafScreen("payment_method")
    object Privacy : LeafScreen("privacy")
    object Security : LeafScreen("security")
    object FAQ : LeafScreen("faq")
    object BestSeller : LeafScreen("best_seller")
    object ProductDetail : LeafScreen("product_detail")
    object Cart : LeafScreen("cart")
    object CreateAccount : LeafScreen("create_account")
    object ChangeEmail : LeafScreen("change_email")
    object ChangePassword : LeafScreen("change_password")
    object Favourites : LeafScreen("favourites")

}